### ISSUE TITLE
ibrowse http client dependency is out of date

### ISSUE THREAD

**Issue by pgporada** [technion/ct_advisor#2]
The current `rebar.config` contains `{ibrowse, {git, "https://github.com/cmullaparthi/ibrowse.git", {tag, "v4.2"}}},` while the ibrowse upstream is at `v4.4.2` per https://github.com/cmullaparthi/ibrowse/blob/master/CHANGELOG.

**Comment by technion** [comment]
Hi,

At this moment, the latest currently tagged is 4.4.1.
I've tested with this version and every single connection returns

{error,enetunreach}

I'm currently investigating.

**Comment by technion** [comment]
This was a frustrating fix.
I've updated to 4.4.0, which is the latest working version of ibrowse.  See some references:

https://github.com/cmullaparthi/ibrowse/issues/167
https://github.com/cmullaparthi/ibrowse/issues/162

You can see 4.4.1 is the latest published version here:

https://github.com/cmullaparthi/ibrowse/releases
