### ISSUE TITLE
Configure a user agent

### ISSUE THREAD

**Issue by pgporada** [technion/ct_advisor#3]
Hi,

Can you please add the ability to configure a user agent and set a default one for this project? I've been trying to track down the various researcher projects that are scraping the Let's Encrypt CT Oak and Testflume logs.

Thank you!

**Comment by technion** [comment]
@pgporada  My apologies for missing this.

I have configured CTAdvisor as the agent used by this code. That said, I'd be very surprised if anyone was using this application to scrape those logs. This tool hardcodes the logs reviewed and those were never on the list.

**Comment by pgporada** [comment]
Thank you! 😀
